name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # 1. КОНФИГУРАЦИЯ СРЕДЫ
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM dependencies for build # <--- Установка зависимостей проекта
        run: npm install

    # 2. ШАГ СБОРКИ SPA
      - name: Install dependencies (SPA)
        run: npm install
        working-directory: spa-app # <--- Установка зависимостей в папке SPA

      - name: Build SPA
        run: npm run build
        working-directory: spa-app # <--- Сборка React-приложения

    # 3. ШАГ ДЕПЛОЯ
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        # Теперь деплоить нужно папку dist, созданную React/Vite
        run: firebase deploy --only hosting --public spa-app/dist --project secret-bangkog
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}