name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. КОНФИГУРАЦИЯ СРЕДЫ
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 2. ШАГ СБОРКИ SPA
      - name: Install SPA Dependencies (in spa-app)
        run: npm install
        working-directory: spa-app # <--- Явно указываем папку для npm install

      - name: Build SPA
        run: npm run build
        working-directory: spa-app # <--- Явно указываем папку для npm run build

      # 3. ШАГ ДЕПЛОЯ
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        # Указываем, что нужно деплоить папку dist из подпапки spa-app
        run: firebase deploy --only hosting --project secret-bangkog --public spa-app/dist
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}